version: '3.8'

services:
  app:
    image: webdevops/php-nginx-dev:8.4
    container_name: app
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/web
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "80:80"
    working_dir: /var/www/html/
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge